baseURL = 'https://example.org/'
languageCode = 'en-GB'
title = 'COMP63301'
theme = 'hugo-theme-relearn'

[params]
  themeVariant = 'manchester'
  hideAuthorEmail = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true